blueprints/select_degree.py
from functions import get_db_connection
from flask import jsonify, request, render_template, redirect, url_for, session, Blueprint
from flask_login import login_required, current_user


select_degree_bp = Blueprint('select_degree', __name__, template_folder='templates')

#Route for when they select only major
@select_degree_bp.route('/select_major', methods=['GET', 'POST'])
@login_required
def select_major():
    if request.method == 'POST':
        college = request.form['college']
        major = request.form['major'].split()[0]
        major_name = request.form['major'].split("-")[-1]
        program = request.form['program']

        prof = request.form['prof']
        session['prof'] = 'None' if prof == 'None' or prof == "" else prof 
        session['degree'] = f'{college}_{major}_{program}'
        session['schedule_id'] = 0
        session['major_name'] = major_name
        courses_selected = []

        return redirect(url_for('courses.planner'))
    return render_template('select_major.html', user=current_user)


@select_degree_bp.route('/compare_degrees', methods=['GET','POST'])
@login_required
def compare_degrees():
    if request.method =='POST':
        degree_count = int(request.form.get('degree_count'))
        degrees = []

        for i in range(1, degree_count + 1):
            college = request.form.get(f'college{i}')
            major = request.form.get(f'major{i}')
            program = request.form.get(f'program{i}')
            if college and major and program:
                degrees.append(f"{college}_{major}_{program}")

        common_courses = {}
        all_courses = {}

        for degree in degrees:
            connection = get_db_connection(degree)
            cursor = connection.cursor(dictionary=True)
            cursor.execute('''
                SELECT rc.CourseID, c.CourseName, rc.Credits
                FROM RequirementCourses rc
                LEFT JOIN Courses.Courses c ON rc.CourseID = c.CourseID
            ''')
            courses = cursor.fetchall()
            connection.close()

            courses_checked = {}
            for course in courses:
                course_id = course['CourseID']
                if 'Credit' in course_id:
                    continue
                if course_id not in courses_checked:
                    if course_id not in all_courses:
                        all_courses[course_id] = 0
                    all_courses[course_id] += 1
                    if all_courses[course_id] == len(degrees):
                        common_courses[course_id] = course
                    courses_checked[course_id] = 'checked'

        return render_template('compare_degrees.html', common_courses=common_courses, degrees=degrees)
    return render_template('compare_degrees.html')


@select_degree_bp.route('/api/majors', methods=['GET'])
@login_required
def get_majors():
    college = request.args.get('college')
    connection = get_db_connection('DegreeData')
    cursor = connection.cursor(dictionary=True)
    cursor.execute('SELECT MajorID, MajorName FROM Majors WHERE CollegeID = %s', (college,))
    majors = cursor.fetchall()
    connection.close()

    major_list = [{'value': major['MajorID'], 'label': major['MajorName']} for major in majors]
    return jsonify(major_list)

@select_degree_bp.route('/api/programs', methods=['GET'])
@login_required
def get_programs():
    major = request.args.get('major')
    connection = get_db_connection('DegreeData')
    cursor = connection.cursor(dictionary=True)
    cursor.execute('SELECT ProgramID, ProgramName FROM Programs WHERE MajorID = %s', (major,))
    programs = cursor.fetchall()
    connection.close()

    program_list = [{'value': program['ProgramID'], 'label': program['ProgramName']} for program in programs]
    return jsonify(program_list)

@select_degree_bp.route('/api/get_major', methods=['GET'])
@login_required
def get_selected_major():
    major = session.get('major_name')
    return jsonify({"major": major})

templates/advisor_portal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Advisor Portal</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses_taken.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/advisor.css') }}">
    
</head>
<body>
    <header>
        <h1>Advisor Portal</h1>
        <div class="header-buttons">
            <button onclick="logout()"><span>Logout</span></button>
            <button onclick="homepage()"><span>Home Page</span></button>
        </div>
    </header>
    <main>

        <section id="compare-degrees">
            <h2>Search for student information</h2>
            <div id="student-search">
                <label for="student-username">Student Search:</label>
                <input type="text" id="username-input" placeholder="Input Student Username">
                <button type="submit" id="search-username-button"><span>Search</span></button>
            </div>
       

            <div id="courses-taken-list">
                <h3>Courses Taken by Student:</h3>
                <ul id="courses-taken-ul">
                    <!-- List of courses taken will be displayed here -->
                </ul>
            </div>

        </section>


        <section id = "student-schedules">
            <div style="display: flex; justify-content: space-between; align-items: center">
                <h2> Students Saved Degree Plans </h2>
            </div>

            <div id="schedule-container">
                <!-- Schedules will be displayed here dynamically -->
            </div>

        </section>
    </main>
    <script src="static/js/advisor_portal.js"></script>
</body>
</html>

templates/compare_degrees.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compare Degrees</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/compare_degrees.css') }}">
</head>

<body>
    <header>
        <h1>Compare Degrees</h1>
        <div class="header-buttons">
            <button onclick="logout()"><span>Logout</span></button>
            <button onclick="homepage()"><span>Home Page</span></button>
        </div>
    </header>
    <main>

        <section id="compare-degrees">
            <h2>Compare Degrees:</h2>
            <form method="POST" action="{{ url_for('select_degree.compare_degrees') }}">
                <label for="degree-count">Number of Degrees to Compare:</label>
                <select id="degree-count" name="degree_count" onchange="updateDegreeSelectionForms()">
                    <option value="2">2 Degrees</option>
                    <option value="3">3 Degrees</option>
                    <option value="4">4 Degrees</option>
                </select>

                <div id="degree-selection-forms">
                    <!-- Degree selection forms will be dynamically added here -->
                </div>

                <button type="submit"><span>Compare</span></button>
            </form>
        </section>


        <section id="common-courses">
            <h2>Common Courses (No General Education Course)</h2>
            <div class="common-courses-containter">
                {%if common_courses %}
                    {% for course_id, course in common_courses.items() %}
                        <div class="common-course-card">
                            <h3>{{ course.CourseID }} - {{ course.CourseName }}</h3>
                            <p>{{ course.Credits }} Credits</p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </section>
    </main>
    <script src="static/js/compare_degrees.js"></script>
</body>

</html>

templates/compare_plans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compare Plans</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <header>
        <h1>Compare Plans</h1>
        <div class="header-buttons">
            <button onclick="logout()"><span>Logout</span></button>
            <button onclick="homepage()"><span>Home Page</span></button>
        </div>
    </header>
    <main class="comparison-container">
        <section class="schedule-container" id="schedule-1">
            <h2 id="schedule-1-title"></h2>
            <div id="schedule-content-1">
                <!-- Schedule 1 semesters and courses will be dynamically inserted here -->
            </div>
        </section>
        <section class="schedule-container" id="schedule-2">
            <h2 id="schedule-2-title"></h2>
            <div id="schedule-content-2">
                <!-- Schedule 2 semesters and courses will be dynamically inserted here -->
            </div>
        </section>
    </main>
    <script src="static/js/compare_plans.js"></script>
</body>
</html>

templates/courses_taken.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compare Degrees</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses_taken.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="static/nice-select2/dist/css/nice-select2.css" rel="stylesheet" />
</head>
<body>
    <header>
        <h1>Compare Degrees</h1>
        <div class="header-buttons">
            <button onclick="logout()"><span>Logout</span></button>
            <button onclick="homepage()"><span>Home Page</span></button>
        </div>
    </header>
    <main>
        <section id="courses-taken">
            <h2>Courses Taken</h2>
            <form id="courses-taken-form" onsubmit="submitCoursesTaken(event)">
                <div id="course-forms-container">
                    <!-- Course input forms will be dynamically added here -->
                    <div class="course-form">
                        <div class="courseDiv">
                            <label for="course-select-0">Select Course:</label>
                            <select id="course-select-0" name="course-0" class="course-select">
                                <!-- Options will be dynamically populated -->
                            </select>
                        </div>

                        <div>
                            <label for="semester-select-0">Select Semester:</label>
                            <select id="semester-select-0" name="semester-0">
                                <option value="AU">Autumn</option>
                                <option value="SP">Spring</option>
                                <option value="SU">Summer</option>
                            </select>
                        </div>

                        <div>
                            <label for="year-select-0">Select Year (last 2 digits):</label>
                            <input type="number" id="year-select-0" name="year-0" min="18" max="24" required>
                        </div>
                    </div>
                    <hr>
                </div>
                <button type="button" onclick="addCourseForm()">Add Another Course</button>
                <button type="submit">Add Courses</button>
            </form>

        </section>

        <section>
            <div id="courses-taken-list">
                <h3>Your Courses Taken:</h3>
                <ul id="courses-taken-ul">
                    <!-- List of courses taken will be displayed here -->
                </ul>
            </div>
        </section>

    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="static/nice-select2/dist/js/nice-select2.js"></script>
    <script src="static/js/courses_taken.js"></script>
</body>
</html>

templates/degree_selection.html
{% if num %}        
<select id="college{{ num }}" name="college{{ num }}" onchange="fetchMajors(this.value, 'major{{ num }}', 'program{{ num }}')">

    <option value="">Select College</option>

    <option value="AGR">
        AGR - Food Agricultural and Environmental Sciences
    </option>

    <option value="AHR">
        AHR - Architecture
    </option>

    <option value="ASC">
        ASC - Arts and Sciences
    </option>

    <option value="ATI">
        ATI - Agricultural Technical Institute
    </option>

    <option value="BUS">
        BUS - Business
    </option>

    <option value="DHY">
        DHY - Dental Hygiene
    </option>

    <option value="EHE">
        EHE - Education and Human Ecology
    </option>

    <option value="ENG">
        ENG - Engineering
    </option>

    <option value="ENR">
        ENR - Environment and Natural Resources
    </option>

    <option value="HRS">
        HRS - Health and Rehabilitation Sciences
    </option>

    <option value="JGS">
        JGS - John Glenn College of Public Affairs
    </option>

    <option value="LAW">
        LAW - Law
    </option>

    <option value="MED">
        MED - Medicine
    </option>

    <option value="NUR">
        NUR - Nursing
    </option>

    <option value="PBH">
        PBH - Public Health
    </option>

    <option value="PHR">
        PHR - Pharmacy
    </option>

    <option value="SWK">
        SWK - Social Work
    </option>
</select>

<select id="major{{ num }}" name="major{{ num }}" onchange="fetchPrograms(this.value, 'program{{ num }}')">
    <option value="">Select Major</option>
    <!-- Majors will dynamically populate -->
</select>

<select id="program{{ num }}" name="program{{ num }}">
    <option value="">Select Program</option>
    <!-- Programs will dynamically populate -->
</select>

{% else %}
<select id="college" name="college" onchange="fetchMajors(this.value, 'major', 'program')">

    <option value="">Select College</option>

    <option value="AGR">
        AGR - Food Agricultural and Environmental Sciences
    </option>

    <option value="AHR">
        AHR - Architecture
    </option>

    <option value="ASC">
        ASC - Arts and Sciences
    </option>

    <option value="ATI">
        ATI - Agricultural Technical Institute
    </option>

    <option value="BUS">
        BUS - Business
    </option>

    <option value="DHY">
        DHY - Dental Hygiene
    </option>

    <option value="EHE">
        EHE - Education and Human Ecology
    </option>

    <option value="ENG">
        ENG - Engineering
    </option>

    <option value="ENR">
        ENR - Environment and Natural Resources
    </option>

    <option value="HRS">
        HRS - Health and Rehabilitation Sciences
    </option>

    <option value="JGS">
        JGS - John Glenn College of Public Affairs
    </option>

    <option value="LAW">
        LAW - Law
    </option>

    <option value="MED">
        MED - Medicine
    </option>

    <option value="NUR">
        NUR - Nursing
    </option>

    <option value="PBH">
        PBH - Public Health
    </option>

    <option value="PHR">
        PHR - Pharmacy
    </option>

    <option value="SWK">
        SWK - Social Work
    </option>
</select>

<select id="major" name="major" onchange="fetchPrograms(this.value, 'program')">
    <option value="">Select Major</option>
    <!-- Majors will dynamically populate -->
</select>

<select id="program" name="program">
    <option value="">Select Program</option>
    <!-- Programs will dynamically populate -->
</select>


{% endif %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OSU Degree Planner</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="static/nice-select2/dist/css/nice-select2.css" rel="stylesheet" />

</head>
<body>
    <header>
        <h1>OSU Degree Planner</h1>
        <div class = "header-buttons">
            <button onclick="logout()"><span>Logout</span></button>
            <button id ="newScheduleBtn"><span>Home Page</span></button>
            <button onclick="saveSchedule()"><span>Save Schedule</span></button>
            <button id="lookupPrereqBtn"><span>Lookup Class Prerequisite</span></button>

        </div>
    </header>
    <div id="prerequisiteModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Lookup Class Prerequisite</h2>
            <input id="courseIDInput" name="courseIDInput" placeholder="Enter Course ID">
            <button id="lookupPrereqSubmit">Submit</button>
            <div id="prerequisiteResult"></div>
        </div>
    </div>

    <div id="newScheduleModal" class="modal">
        <div class="modal-content">
            <h2>Do You Want To Save This Schedule?</h2>
            <button id="newScheduleYes">Yes</button>
            <button id="newScheduleNo">No (Return back to Home Page)</button>
        </div>
    </div>

    <div id="loadedScheduleModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Do You Want To Update The Current Schedule Or Create A New One?</h2>
            <button id="loadedScheduleUpdate">Update</button>
            <button id="loadedScheduleNew">Create New</button>
        </div>
    </div>

    <div id="saveScheduleModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Enter A Name For Your Schedule:</h2>
            <input type="text" id="scheduleNameInput" placeholder="Enter Schedule Name">
            <button id="schdeuleNameSubmit">Submit</button>
        </div>
    </div>

    <div id="messageModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2 id="message"></h2>
            <div style="display:flex;">
                <div id="messageDiv"></div>
                <img src="/static/imgs/sadbrutus.png">
            </div>
            <button id="messageOkay">OK</button>
        </div>
    </div>

    <div id="waitModal" class="modal">
        <div class="modal-content" style="text-align: center;">
            <h2 id="waitMessage">Please Wait Your Degree Plan Is Being Loaded</h2>
            <div class="loader"></div>
        </div>
    </div>

    <div id="validCoursesModal" class="modal">
        <div class="modal-content requirement">
            <span class="close">&times;</span>
            <ul id="validCourses" style="text-align: center;"></ul>
            <button id="validCoursesOkay">OK</button>
        </div>
    </div>

    
    <main>
        <section id="semester-planner">
            <h2>Semester Planner</h2>
            <div>
                <h5 id="manualCourseHeading">Manually Add Course</h5>
                <input placeholder="Enter Course ID"id="manualCourseInput" name="manualCourseInput">
                <datalist id="manualCourseDataList" placeholder="Enter Course ID">
                    <!-- Options will be dynamically populated -->
                </datalist>
                <select id="manualSemesterSelect">
                    <!-- Options will be dynamically populated -->
                </select>
                <button onclick="addManualCourse()">Add Course</button>
            </div>
            

            <div id="semester-rows">
                <!-- Semester rows will be added dynamically here -->
            </div>

            <div id = 'add-semester-div'>
                <button id='add-semester-button' onclick="addSemester()">Add Semester</button>
                <button id='remove-semester-button' onclick="removeSemester()">Remove Semester</button>
            </div>
        </section>

        <section id="degree-requirements-container">
            <h2>Degree Requirements</h2>
            <h3 data-credits="0" id="totalCredits" style="margin: 1px;">Total Credit Hours: 0</h3>
            <h5 style="margin-top: 5px; ">Click on course to see prerequisites; Drag and Drop course into planner</h5>
            <!-- <h5 style="margin-top: 5px;">Drag and Drop course into planner</h5> -->
            <div id="degree-requirements">
                <!-- Degree requirements will be displayed here by JavaScript -->
            </div>
        </section>

    </main>

    <input type="hidden" id="schedule-id" value="{{ schedule_id }}">
    <input type ="hidden" id="prof" value="{{ prof }}">
    <input type="hidden" id="sample-schedule-id" value="{{ sample_schedule_id }}">


    <script src="static/nice-select2/dist/js/nice-select2.js"></script>
    <script src="static/js/script.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome Back</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">

</head>
<body>
    <div class="login-page">
        <div class="container">
            <form id="loginForm"class="login-form" method="POST" action="{{ url_for('login') }}">
                <h2><i class="fas fa-user"></i> Welcome Back</h2>
                <p class="subtitle">Please log in to your account</p>
                <div class="input-container">
                    <input type="text" id="username" name="username" required>
                    <label for="username">Username</label>
                    <i class="fas fa-user"></i>
                </div>
                <div class="input-container">
                    <input type="password" id="password" name="password" required>
                    <label for="password">Password</label>
                    <i class="fas fa-lock"></i>
                </div>

                <div class="checkbox-container">
                    <input type="checkbox" id="show-password" onclick="unHidePassword()">
                    <label for="show-password">Show Password</label>
                </div>

                <button type="submit">Login</button>
                <p class="signup-link">Don't have an account? <a href="/register">Sign up</a></p>
            </form>
        </div>
    </div>

    <script> 

        function unHidePassword(){
            const password = document.getElementById('password');
            if (password.type === 'password'){
                password.type = 'text'
            } else {
                password.type = 'password'
            }
        }

    </script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <style>
        .error {
            color: red;
            display: none;
        }
    </style>
</head>
<body>
    <div class="login-page">
        <div class="container">
            <form id="registerForm" class="login-form" method="POST" action="{{ url_for('login') }}">
                <h2><i class="fas fa-user"></i> Sign Up</h2>
                <p class="subtitle">Please create your account</p>
                <div class="input-container">
                    <input type="text" id="username" name="username" required>
                    <label for="username">Username</label>
                    <i class="fas fa-user"></i>
                </div>
                <div class="input-container">
                    <input type="password" id="password" name="password" required>
                    <label for="password">Password</label>
                    <i class="fas fa-lock"></i>
                </div>

                <div class="input-container">
                    <input type="password" id="confirmPassword" name="confirmPassword" required>
                    <label for="confirmPassword">Confirm Password</label>
                    <i class="fas fa-lock"></i>
                </div>

                <div class="checkbox-container">
                    <input type="checkbox" id="show-password" onclick="unHidePassword()">
                    <label for="show-password">Show Password</label>
                </div>

                <span id="error" class="error">Passwords do not match</span>
                <span id="usernameError" class="error">Username is already taken</span>
                <button type="submit">Register</button>
                <p class="signup-link">Already have an account? <a href="{{ url_for('login') }}">Login here</a></p>
            </form>
        </div>
    </div>
    <script src="static/js/register.js"></script>
</body>
</html>

templates/select_major.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select Degree</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <header>
        <h1>Select Degree</h1>
        <h5> Home Page </h5>
        <div class="header-buttons">
            <button onclick="logout()"><span>Logout</span></button>
        </div>
    </header>
    <main>
        <section id="major-selection">
            <form method="POST" action="{{ url_for('select_degree.select_major') }}">
                <h2>Select Degree:</h2>
                {% include 'degree_selection.html' %}
                <button type="submit">
                    <span>Submit</span>
                </button>
            </form>
        </section>

        <section id="middle-section">
            <section id="compare-degrees">
                <form method="GET" action="{{ url_for('select_degree.compare_degrees')}}">
                    <h2>Compare Degrees: </h2>
                    <button type="submit">
                        <span>Go to Compare Degrees</span>
                    </button>
                </form>
            </section>

            <section id="courses-taken">
                <h2>Courses Taken: </h2>
                <form method="GET" action="{{ url_for('courses.courses_taken')}}">
                    <button type="submit">
                        <span>Input Courses Taken Here</span>
                    </button>
                </form>
            </section>
        </section>

        <section id="saved-schedules">
            <h2>Your Saved Degree Plans</h2>
            <div class="buttons-container">
                <button class="resize-button" onclick="document.getElementById('importScheduleInput').click();"><span>Import Plan</span></button>
                <button class="resize-button" onclick="checkAndOpenComparePlansModal()"><span>Compare Saved Plans</span></button>
                <input type="file" id="importScheduleInput" style="display:none" onchange="importSchedule(event)">
            </div>
            <div id="schedule-container">
                <!-- Schedules will be displayed here dynamically -->
            </div>
        </section>
    </main>

    <div id="comparePlansModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeComparePlansModal()">&times;</span>
            <h2>Select Two Plans to Compare</h2>
            <div id="plans-selection">
                <!-- Plans selection checkboxes will be populated here -->
            </div>
            <button id="compare-button">Compare</button>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/select_degree.js') }}"></script>
</body>
</html>